### ISSUE TITLE
接口压力分流

### ISSUE THREAD

**Issue by BlankerL** [shfshanyue/2019-ncov#12]
您好，我是[DXY-2019-nCoV-Crawler](https://github.com/BlankerL/DXY-2019-nCoV-Crawler)的开发者。

近期项目的API流量压力较大，看到您的项目使用人数较多，并且正在使用我的API，想请问您能否在后端设置一个缓存，定期储存API的内容更新，前端直接加载后端的缓存数据，而不是所有用户每次访问都请求API接口呢？目前我的API服务器设置在香港，受GFW的限制，入境的速率基本上只有5Mbps，等后续域名备案完成并迁移到大陆后，您可以再通过前端直接请求API。万分感谢！

另外，我的项目遵循MIT协议，请问您能否在README中备注使用本API？

**Comment by shfshanyue** [comment]
您好，本项目在前期中使用了您的 API，在脚本中 build.js 中，不过有一天挂掉了，**于是就没有再次使用您的 API。**

现在的使用方式是使用脚本 build-origin.js 每隔半个小时从**丁香园**抓一次数据直接注入前端，所以对丁香园的压力也很小。

**Comment by BlankerL** [comment]
> 您好，本项目在前期开发时使用了您的 API，在脚本中 build.js 中，不过有一天挂掉了(七天前)，**于是就没有再次使用您的 API。**
> 
> 现在的使用方式是使用脚本 build-origin.js 每隔半个小时从**丁香园**抓一次数据直接注入前端 (每半个小时就自动部署一次)，所以对丁香园的压力也很小。您可以在我的前端页面中发现疫情数据是写死的，并没有发送请求。
> 
> 您的数据很详细，我目前贴在 README 中做了推荐

万分感谢！

因为域名没有备案，服务器80/443端口都打不开，所以只能把网站架设在香港的服务器。然而入境流量十分有限，所以本来希望能分流一下。

如果能直接从丁香园中半小时获取一次数据会更好啦～

我也在项目中推荐了这一个解决方案。再次感谢！
