### ISSUE TITLE
建议使用 Cloudflare Worker 替代 build-origin.js 实现实时数据接口

### ISSUE THREAD

**Issue by lsongdev** [shfshanyue/2019-ncov#3]
Nice work!

刚好我也在做类似的事情，关于丁香园的页面到接口的转换可以试试 Cloudflare Worker 功能。

FYI: https://github.com/song940/2019-ncov/blob/master/dxy.cfw.js

**Comment by shfshanyue** [comment]
感谢建议！

Cloudfare Worker 是一个很好的思路，避免了定时部署，只是有点担心时延问题。

阿里云的 serverless 应该也是一个不错的可替代选择。
