### ISSUE TITLE
建议修改命名“武汉肺炎”

### ISSUE THREAD

**Issue by yzhu01** [shfshanyue/2019-ncov#9]
建议您将命名中“武汉肺炎”修改为官方的命名，以防引发基于地域的偏见与歧视。

> 以下是来自WHO的参考：
Terms that should be avoided in disease names include geographic locations (e.g. Middle East Respiratory Syndrome, Spanish Flu, Rift Valley fever), people’s names (e.g. Creutzfeldt-Jakob disease, Chagas disease), species of animal or food (e.g. swine flu, bird flu, monkey pox), cultural, population, industry or occupational references (e.g. legionnaires), and terms that incite undue fear (e.g. unknown, fatal, epidemic).
Link: https://www.who.int/mediacentre/news/notes/2015/naming-new-diseases/en/

非常感谢🙏

**Comment by shfshanyue** [comment]
ok

**Comment by yzhu01** [comment]
感谢您的回复。
Resolved
